title: "16S rRNA è§£æ å…±é€šãƒ—ãƒ­ãƒˆã‚³ãƒ«"
description: "QIIME2 / PICRUSt2 å…±é€šæ‰‹é †ï¼ˆver. 2024.05ï¼‰"
theme: minima
markdown: kramdown

# ğŸ”½ ã“ã‚Œã‚’è¿½åŠ 
url: "https://serol1.github.io"
baseurl: "/qiime2_analysis_manual"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

include:
  - _includes
